server:
  port: 8001

spring:
  application:
    name: 001-eureka-client-consumer

eureka:
  client:
    service-url:
      defaultZone: http://eureka6001:6001/eureka, http://eureka6002:6002/eureka

      #省略默认操作   注册到注册中心、拉取注册中心列表
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
